[Tribute Page](https://codepen.io/chtotoyest/full/RwwpRLp)
[Survey Form](https://codepen.io/chtotoyest/full/rNNyWjp)
[Technical Documentation](https://codepen.io/chtotoyest/full/wvBvXwP)
[Simple Landing Page](https://codepen.io/chtotoyest/full/bGGrYvw)
[Personal Portfolio](https://marinaandthecode.github.io/personal-portfolio/)
